# Site settings
title: Home
description: >- # this means to ignore newlines until "baseurl:"

  Adilson Menechini.
  We DevOps deliver products.

baseurl: "/"  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#repository: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name          : Adilson Menechini
  image         : /images/perfil.jpeg
# behance       : your_username
# dribbble      : your_username
  email         : adilsonmenechini@gmail.com
  facebook      : adilsonmenechini
  github        : adilsonmenechini
  gitlab        : adilsonmenechini
# instagram     : your_username
  linkedin      : adilsonmenechini
# medium        : your_username
# soundcloud    : your_username
# spotify       : your_username
# stackoverflow : your_user_id
# tumblr        : your_username.tumblr.com
# twitch        : your_username
  twitter       : dilsonmenechini
# vimeo         : your_username
# youtube       : your_channel_name

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock